probberechts/soccerdata

soccerdata/fbref.py
This PR add's support for scraping tournaments, such as the World Cup (see #99).
=> [FBref] Add support for tournaments

.github/workflows/ci.yml, noxfile.py, poetry.lock, pyproject.toml
This enables upgrading Poetry and Sphinx to the latest version.
=> Drop Python 3.7 support

soccerdata/_config.py, soccerdata/fbref.py, soccerdata/whoscored.py
This PR adds support for scraping data for the 2023 Women's World Cup from FBref and WhoScored.
Fixes #299
=> Add support for Women's World Cup

docs/reference/fbref.rst
Adds the read_leagues, read_seasons, read_team_match_stats, and read_events methods to the API docs.
=> [FBref] Update API docs

poetry.lock, pyproject.toml
=> Update dependency undected-chromedriver to v3.5.0

soccerdata/sofifa.py
SoFIFA made some changes to its website, breaking the "read_leagues" function.
Fixes #317
=> [SoFIFA] Fix read_leagues

soccerdata/fbref.py
specially take care of the URL when read_team_match_stats is on the latest (unfinished) season
=> update read_team_match_stats to deal with latest season

soccerdata/fbref.py
=> [FBref] exception if opponent stats not available

soccerdata/sofifa.py
Update to match new HTML structure for displaying team names on SoFIFA.
Fixes #413
=> [SoFIFA] Fix team xpath selector

soccerdata/sofifa.py
This commit adapts the SoFIFA reader to work with the new HTML structure. Furthermore, it extends the number of ratings scraped by "read_team_ratings".
Make sure to delete the SoFIFA cache before updating!
Fixes #449
=> [SoFIFA] Adjust to new HTML structure

noxfile.py
This pull request closes #479.
=> [Nox] Replace tilde with Path.home()

soccerdata/espn.py
=> [ESPN] Allow new roster format

poetry.lock, pyproject.toml, soccerdata/_common.py
=> [SoFIFA] Bypass Cloudflare's anti-bot page

soccerdata/fbref.py
- Reduce unnecessary scraping by attempting to read previous seasons from cache. Like #97 , this can be problematic at season start (in this case if a previous season hasn't been fully cached).
- Keep consistency with other FBref methods.
=> [FBref] Add force_cache param to read_team_match_stats

soccerdata/fbref.py
When the FBref reader was initialized with leagues=["Big 5 European Leagues Combined", ...] where ... contains other leagues from the Big 5 (e.g., "ENG-Premier League") it would scrape the league twice.
Fixes #576
=> [FBref] Avoid duplicate Big 5 leagues

tests/test_FBref.py
=> Add test for FBref.available_leagues

poetry.lock, pyproject.toml
=> fix(deps): add "packaging"

poetry.lock, pyproject.toml
Adds socceraction to the lock file to ensure the dependencies are compatible.
See https://github.com/ML-KULeuven/socceraction/issues/797
=> fix(deps): ensure compatability with socceraction

soccerdata/match_history.py
=> [MatchHistory] old seasons use short year format

soccerdata/fotmob.py
FotMob now requires a "x-fm-req" value to be present in the header.
Fixes #742
=> [FotMob] patch for new anti-scraping header

CONTRIBUTING.rst, soccerdata/_common.py, soccerdata/clubelo.py, soccerdata/fbref.py, soccerdata/fotmob.py, soccerdata/sofifa.py, tests/appdata/config/teamname_replacements.json, tests/test_FBref.py, tests/test_FotMob.py, tests/test_SoFIFA.py, tests/test_common.py
=> [ClubElo, FotMob, SoFIFA, FBREF] Fixing and unifying TEAMNAME_REPLACEMENTS loading

soccerdata/whoscored.py
=> [WhoScored] update URL parsing

soccerdata/sofifa.py
=> Player ratings in SoFIFA

poetry.lock, pyproject.toml, soccerdata/_common.py, soccerdata/clubelo.py, soccerdata/espn.py, soccerdata/fbref.py, soccerdata/fotmob.py, soccerdata/match_history.py, soccerdata/sofascore.py, soccerdata/sofifa.py, soccerdata/understat.py, soccerdata/whoscored.py, tests/conftest.py
undetected_chromedriver is no longer maintained.
Fixes #829
=> Replace undetected_chromedriver by seleniumbase

soccerdata/fbref.py
Increase from 6 requests / sec to 7 requests / sec to avoid being blocked.
=> [FBref] Increase rate limit
