soccerdata/fbref.py
FBRef appears to have switched to using `year_id` as the `data-stat` attribute on its seasons table.
This change allows the `read_seasons` function to return the expected seasons.
=> FBRef - replace 'season' data stat with 'year_id'

.github/workflows/ci.yml, .github/workflows/release.yml, docs/requirements.txt, poetry.lock, pyproject.toml, soccerdata/_config.py, soccerdata/fbref.py, tests/conftest.py, tests/test_FBref.py
I am having another go at this [previous attempt #69] because you have updated the FBRef class to use the league pages. I have tried this against all stat_types for 2020-2021 and it seems to work
- Amended the FBRef scraper so it uses the Big 5 pages if all five leagues are requested.
- Added some type checks for the stats_type argument.
I am not able to run the tests locally, but I'll try to fix anything that doesn't work after.
=> Faster scraping of player seasons stats - fbref.

soccerdata/match_history.py
The CSV files provided by football-data.co.uk sometimes contain a few empty columns at the end. These are now dropped from the output dataframe.
=> [MatchHistory] Drop empty cols

soccerdata/fbref.py
The filename for the cached team season stats was appended with "all", regardless of the type of stats queried. This caused an issue as the cache might not have contained the table needed. It now caches these tables in different files.
=> [FBref] Fix invalid cache filenames in read_team_season_stats

soccerdata/fbref.py
The method _fix_nation_col throws an IndexError, supposedly when no flag is present. I fixed this by changing the logic to use regular expressions instead so that no error is thrown when the flag is missing.
=> [FBref] Handle missing flag icon in Squad or Nation column

soccerdata/fbref.py
The fbref.read_team_match_stats() method returned the match logs from all available competitions, ignore the leagues configured in the contstructor.
=> [FBref] filter leagues in read_team_match_stats

soccerdata/fbref.py, tests/test_FBref.py
The FBref scraper attempts to merge data from multiple games, seasons, etc. in a single DataFrame. Sometimes this automatic merge fails, in which case a cryptic error is thrown. Now, a more informative error message is printed listing the additional and/or missing columns and with the suggestion to clear the cache (a common cause is merging new with outdated cached data).
Fixes #161
=> [FBref] Informative errors when merge fails

soccerdata/fbref.py
When two players in the same team have identical names, the output of the read_lineups function would return duplicates. This is fixed by using the jersey number as an additional merge key.
Fixes #305
=> [FBref] Handle teammates with identical name

soccerdata/fbref.py, tests/test_FBref.py
_concat would throw an error when analysing [Tottenham-Rennes](https://fbref.com/en/matches/d69a0a11/Tottenham-Hotspur-Rennes-December-9-2021-Europa-Conference-League), as the game was forfeited and, therefore, there is no match data available for it. The dataframe resulting from this page had fewer columns than the ones for other games in the competition, thus throwing an error.
This is a new attempt to solve #304.
=> Handle canceled / forfeited games

.github/workflows/ci.yml, poetry.lock, pyproject.toml
- Drop Python 3.8 support
- Update pandas to v2.1.1
- Mark pandas v2.1.0 as not supported (fixes #372)
=> Drop Python 3.8 support

soccerdata/_common.py, soccerdata/whoscored.py
Selenium does no longer support headless mode for version 4.13 and above. This was added to the docs and a warning is raised if headless mode is enabled for a recent version of Selenium.
Also adds a temporary fix for undetected-chromedriver, setting "headless" explicitly to False, such that soccerdata can still be used with recent versions of selenium.
Fixes #398
=> Handle Selenium 4.13 no longer supporting headless

soccerdata/_common.py, soccerdata/whoscored.py
Hello, @probberechts.
I propose a solution to the problem of empty files in the cache for Whoscored.
In issue [98](https://github.com/probberechts/soccerdata/issues/98) you suggest delete empty file with bash command by file size.
I made method `_size_file` which does same with `Path.stat().st_size`. If the file is smaller than threshold, we believe that it is not cached
```python
def _size_file(
self,
filepath: Optional[Path] = None,
filter_size: int = 60
) -> bool:
"""Check if `filepath` contains data valid size.
Parameters
----------
filepath : Path, optional
Path where file should be cached. If None, return False.
filter_size : int file size threshold. If file is smaller, return False
Raises
------
TypeError
If filter_size is not an integer.
Returns
-------
bool
True in case of a …
```
=> [WhoScored] Ignore cached events file if empty

docs/intro.rst, soccerdata/_common.py, soccerdata/_config.py
This commit adds a "SOCCERDATA_MAXAGE" environment variable. If set, cached data that is older than the configured max-age will be re-downloaded. This is useful for testing. We want to check regularly whether the scrapers can still parse the remote data, but downloading all data in each test run is too slow.
=> Add option to configure caching max-age via env

docs/datasources/index.rst
I changed "Detailed scores on all player's abilities from EA Sports FIFA." to "Detailed scores on all player's abilities from EA Sports FC." as the name of the game changed in September 2023.
=> Rename FIFA --> EA Sports FC

soccerdata/fotmob.py
This fixes the issue brought up in #528 where the `opponent_stats=True` parameter setting returned only the opponent stats, but incorrectly labelled as the requested team's stats. When `opponent_stats=True`, the correctly labelled match stats for both teams should now be returned.
=> [FotMob] Get correct team match stats using 'opponent_stats' parameter

soccerdata/_common.py, soccerdata/whoscored.py
- Adds a "retry_missing" option to the read_events method to control whether to retry or skip games for which no events are available.
- Adds a "skip_on_error" option to the read_events method to control whether to raise an exception or skip the match when the match page cannot be retrieved.
=> [WhoScored] Add options to skip/retry/raise when scraping match events fails

soccerdata/_common.py, soccerdata/_config.py, soccerdata/fbref.py, soccerdata/fotmob.py, soccerdata/sofascore.py, soccerdata/understat.py, soccerdata/whoscored.py, tests/test_common.py
This commit adds support for single-year season codes (e.g,. 2023) that are used in leagues such as the MLS, in contrast to the multi-year season codes (e.g., 2023/24) typically used in European football.
=> Support single-year season codes

soccerdata/whoscored.py
Fixes the `read_events` method. WhoScored changed the Javascript variable that stores the data.
Fixes #617
=> [WhoScored] Fix javascript error: requirejs is not defined

soccerdata/fotmob.py
Currently only games which were concluded in standard time are returned from read_match_stats as the status code for games that were decided in extra time or by penalties do not have the "FT" status.
I am re-raising this PR as the previous PR failed on the codecov check as it wasn't enabled on my repository when I made the PR, and I could not see how to trigger another check, and would rather just re-raise the PR than push a dummy commit.
=> [Fotmob] Include matches which ended in extra time or after penalties 

soccerdata/_common.py, soccerdata/whoscored.py
Previously, the javascript variable that stores all events was empty when no events were available for a given game. Since the change fixed in #618, the javascript variable is missing instead, resulting in a `JavascriptException`. This commit updates the error handling accordingly.
Closes #633
=> [WhoScored] Error handling for missing events

soccerdata/fbref.py
FBref has increased rate limiting from twenty to ten requests per minute. See <https://www.sports-reference.com/bot-traffic.html>.
Fixes #668
=> [FBref] Update rate limit to 10 requests/sec

soccerdata/sofascore.py
Adds support for adding custom leagues that are not one of the 'top-tournaments'.
Fixes #679
=> feat(sofascore): support 2nd tier leagues

.github/workflows/ci.yml
From September 2nd, 2024, the GitHub action update-artifact does not upload hidden files and folders by default. This caused trouble with .coverage files.
=> Fix missing coverage upload

soccerdata/sofifa.py
=> [SoFIFA] Update parsing of player profile page

poetry.lock, pyproject.toml, soccerdata/_common.py
Sofascore now uses TLS fingerprinting to detect bots. This PR uses the `tls-requests` to bypass TLS Fingerprinting.
=> [Sofascore] Bypass TLS fingerprinting

soccerdata/sofifa.py
Fix iteration indent error in `SoFIFA.read_player_ratings`
- Test code:
- Before fixing: method `read_player_ratings` would return only one line information
- After fixing:
=> fix(SoFIFA): fix iteration indent error in read_player_ratings
